---

roles:
  - name: clusterverse
    src: https://github.com/dseeley/clusterverse
    version: master

  - name: kubernetes
    src: https://github.com/dseeley/kubernetes-essentials-ansible
    version: master
